/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminPanel.java
 *
 * Created on Nov 21, 2011, 3:14:16 PM
 */
package pos_pbs.PresentationLayer;

import pos_pbs.Util.Util;

/**
 *
 * @author kurtbadelt
 */
public class AdminPanel extends javax.swing.JPanel {

    /** Creates new form AdminPanel */
    public AdminPanel() {
        initComponents();
        DataBaseEdit dbe = new DataBaseEdit();
        this.add(dbe);
        Util util = new Util();
        this.setSize(util.getScreenWith(), util.getScreenHeight());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(805, 605));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
