/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Nov 19, 2011, 6:27:08 PM
 */
package pos_pbs.PresentationLayer;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.UIManager;
import pos_pbs.DataBaseLayer.LocalDBDriver;
import pos_pbs.DataLayer.User;
import pos_pbs.Util.Util;

/**
 *
 * @author kurtbadelt
 */
public final class MainFrame extends javax.swing.JFrame {

    Util util = new Util();
    private int userProfile;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        customInterface();
    }

    public void customInterface() {
        //this is how to add tabls

        this.setMinimumSize(new Dimension(800, 600));
        int tamx = util.getScreenWith();
        int tamy = util.getScreenHeight();
        this.setSize(tamx, tamy);
        jSplitPane1.setSize(tamx - 50, tamy - 50);
        this.setLocation(tamx / 4, tamy / 4);
        this.jButtonAdmin.setEnabled(false);
        this.jButtonOrderProcesing.setEnabled(false);
        this.jButtonRecieve.setEnabled(false);
        this.jButtonReports.setEnabled(false);
        this.jButtonDBUpdate.setEnabled(false);
        this.jButtonOpex.setEnabled(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelMenu = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonOrderProcesing = new javax.swing.JButton();
        jButtonRecieve = new javax.swing.JButton();
        jButtonReports = new javax.swing.JButton();
        jButtonAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonDBUpdate = new javax.swing.JButton();
        jButtonOpex = new javax.swing.JButton();
        jPanelLogin = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        JLabelUserName = new javax.swing.JLabel();
        jPasswordFieldUserName = new javax.swing.JPasswordField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jLabelNotification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(1);

        jPanelMenu.setLayout(new java.awt.GridBagLayout());

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Salir.png"))); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 225, 0);
        jPanelMenu.add(jButtonExit, gridBagConstraints);

        jButtonOrderProcesing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/OrderPro.png"))); // NOI18N
        jButtonOrderProcesing.setText("Order Processing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
        jPanelMenu.add(jButtonOrderProcesing, gridBagConstraints);

        jButtonRecieve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RecieveShip.png"))); // NOI18N
        jButtonRecieve.setText("Recieve Shipment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 0, 0);
        jPanelMenu.add(jButtonRecieve, gridBagConstraints);

        jButtonReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Reports.png"))); // NOI18N
        jButtonReports.setText("Reports");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMenu.add(jButtonReports, gridBagConstraints);

        jButtonAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Admin.png"))); // NOI18N
        jButtonAdmin.setText("Admin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMenu.add(jButtonAdmin, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RedLogo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(138, 1, 0, 0);
        jPanelMenu.add(jLabel1, gridBagConstraints);

        jButtonDBUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/database_refresh.png"))); // NOI18N
        jButtonDBUpdate.setText("DB Update");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMenu.add(jButtonDBUpdate, gridBagConstraints);

        jButtonOpex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/money.png"))); // NOI18N
        jButtonOpex.setText("Opex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMenu.add(jButtonOpex, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanelMenu);

        jPanelLogin.setLayout(new java.awt.GridBagLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipady = -23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 200, 0, 287);
        jPanelLogin.add(jLabelLogo, gridBagConstraints);

        JLabelUserName.setText("User Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(293, 353, 0, 0);
        jPanelLogin.add(JLabelUserName, gridBagConstraints);

        jPasswordFieldUserName.setText("kurtB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(287, 31, 0, 0);
        jPanelLogin.add(jPasswordFieldUserName, gridBagConstraints);

        jLabelPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 353, 0, 0);
        jPanelLogin.add(jLabelPassword, gridBagConstraints);

        jPasswordFieldPassword.setText("#Include1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 31, 0, 0);
        jPanelLogin.add(jPasswordFieldPassword, gridBagConstraints);

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel.png"))); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 353, 0, 0);
        jPanelLogin.add(jButtonCancel, gridBagConstraints);

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/OK.png"))); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 114, 0, 0);
        jPanelLogin.add(jButtonOK, gridBagConstraints);

        jLabelNotification.setText("Enter your User Name and Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 353, 317, 0);
        jPanelLogin.add(jLabelNotification, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanelLogin);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        if (login()) {
            jLabelNotification.setText("Success");
            AdminPanel admin = new AdminPanel();
            jSplitPane1.setRightComponent(admin);



            //cancel();
        } else {
            jLabelNotification.setText("UserName or Password are wrong");
        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        cancel();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed

        cancel();         jSplitPane1.setRightComponent(jPanelLogin);     }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.mac.MacLookAndFell");
            UIManager.setLookAndFeel("com.apple.laf.AquaLookAndFeel");


        } catch (final Exception ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelUserName;
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDBUpdate;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonOpex;
    private javax.swing.JButton jButtonOrderProcesing;
    private javax.swing.JButton jButtonRecieve;
    private javax.swing.JButton jButtonReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNotification;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JPasswordField jPasswordFieldUserName;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    public boolean login() {
        LocalDBDriver ldb = new LocalDBDriver();
        String passwrd = "";
        ldb.createConnection();
        User user = null;

        char[] userInput = jPasswordFieldUserName.getPassword();
        String userName = new String(userInput);


        ArrayList al = ldb.selectUserByUserName(userName);

        if (al.size() > 0) {

            user = (User) al.get(0);

            try {
                passwrd = util.decryptString(user.getPassword());
            } catch (Exception ex) {

                util.writeErrorToLog(ex, "LoginForm_logIn");
            }

            char[] passwordInput = jPasswordFieldPassword.getPassword();
            String pas = new String(passwordInput);

            if (pas.equals(passwrd)) {

                util.writeStringToLog(user.getFirstName() + user.getLastName(), "UserLoged");
                this.userProfile = user.getUserTypeID();
                if (userProfile == 1) {
                    this.jButtonAdmin.setEnabled(true);
                    this.jButtonOrderProcesing.setEnabled(true);
                    this.jButtonRecieve.setEnabled(true);
                    this.jButtonReports.setEnabled(true);
                    this.jButtonDBUpdate.setEnabled(true);
                    this.jButtonOpex.setEnabled(true);
                } else {
                    this.jButtonAdmin.setEnabled(false);
                    this.jButtonOrderProcesing.setEnabled(true);
                    this.jButtonRecieve.setEnabled(true);
                    this.jButtonReports.setEnabled(false);
                    this.jButtonDBUpdate.setEnabled(true);
                    this.jButtonOpex.setEnabled(true);
                }


                return true;
            }
        } else {
            jLabelNotification.setText("User or Password not valid");
            jPasswordFieldPassword.setText("");
            jPasswordFieldUserName.setText("");

        }

        return false;
    }

    /**
     * 
     */
    public void cancel() {
        jPasswordFieldPassword.setText("");
        jPasswordFieldUserName.setText("");
        jLabelNotification.setText("Enter your User Name and Password");
        this.jButtonAdmin.setEnabled(false);
        this.jButtonOrderProcesing.setEnabled(false);
        this.jButtonRecieve.setEnabled(false);
        this.jButtonReports.setEnabled(false);
        this.jButtonDBUpdate.setEnabled(false);
        this.jButtonOpex.setEnabled(false);
    }
}
